#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Feb 17 14:55:51 PST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/ace/tools/Xilinx/Vivado/2024.2/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L blk_mem_gen_v8_4_9 -L fifo_generator_v13_1_5 -L xdma_v4_1_31 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L generic_baseblocks_v2_1_2 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_33 -L fifo_generator_v13_2_11 -L axi_data_fifo_v2_1_32 -L axi_crossbar_v2_1_34 -L axi_protocol_converter_v2_1_33 -L axi_clock_converter_v2_1_32 -L axi_dwidth_converter_v2_1_33 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot PCIe_wrapper_behav xil_defaultlib.PCIe_wrapper xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L blk_mem_gen_v8_4_9 -L fifo_generator_v13_1_5 -L xdma_v4_1_31 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L generic_baseblocks_v2_1_2 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_33 -L fifo_generator_v13_2_11 -L axi_data_fifo_v2_1_32 -L axi_crossbar_v2_1_34 -L axi_protocol_converter_v2_1_33 -L axi_clock_converter_v2_1_32 -L axi_dwidth_converter_v2_1_33 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot PCIe_wrapper_behav xil_defaultlib.PCIe_wrapper xil_defaultlib.glbl -log elaborate.log

